// This file is auto-generated by @hey-api/openapi-ts

export {
  getV1Me,
  headV1Me,
  type Options,
  patchV1Me,
  postV1TtsSpeak,
} from "./sdk.gen";
export type {
  ClientOptions,
  GetV1MeData,
  GetV1MeError,
  GetV1MeErrors,
  GetV1MeResponse,
  GetV1MeResponses,
  HeadV1MeData,
  HeadV1MeErrors,
  HeadV1MeResponses,
  PatchV1MeData,
  PatchV1MeError,
  PatchV1MeErrors,
  PatchV1MeResponse,
  PatchV1MeResponses,
  PostV1TtsSpeakData,
  PostV1TtsSpeakError,
  PostV1TtsSpeakErrors,
  PostV1TtsSpeakResponse,
  PostV1TtsSpeakResponses,
} from "./types.gen";
