// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from "./client";
import { client } from "./client.gen";
import type {
  GetV1AdminAnalyticsData,
  GetV1AdminAnalyticsErrors,
  GetV1AdminAnalyticsResponses,
  GetV1MeData,
  GetV1MeErrors,
  GetV1MeResponses,
  HeadV1AdminAnalyticsData,
  HeadV1AdminAnalyticsErrors,
  HeadV1AdminAnalyticsResponses,
  HeadV1MeData,
  HeadV1MeErrors,
  HeadV1MeResponses,
  PatchV1MeData,
  PatchV1MeErrors,
  PatchV1MeResponses,
  PostV1AnalyticsEventsData,
  PostV1AnalyticsEventsErrors,
  PostV1AnalyticsEventsResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Get current user
 *
 * Returns the authenticated user's profile, including email verification status, role, and account creation date.
 */
export const getV1Me = <ThrowOnError extends boolean = false>(
  options?: Options<GetV1MeData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetV1MeResponses,
    GetV1MeErrors,
    ThrowOnError
  >({ url: "/v1/me", ...options });

/**
 * Get current user
 *
 * Returns the authenticated user's profile, including email verification status, role, and account creation date.
 */
export const headV1Me = <ThrowOnError extends boolean = false>(
  options?: Options<HeadV1MeData, ThrowOnError>,
) =>
  (options?.client ?? client).head<
    HeadV1MeResponses,
    HeadV1MeErrors,
    ThrowOnError
  >({ url: "/v1/me", ...options });

/**
 * Update profile
 *
 * Updates the authenticated user's profile fields (name and/or image).
 */
export const patchV1Me = <ThrowOnError extends boolean = false>(
  options?: Options<PatchV1MeData, ThrowOnError>,
) =>
  (options?.client ?? client).patch<
    PatchV1MeResponses,
    PatchV1MeErrors,
    ThrowOnError
  >({
    url: "/v1/me",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });

/**
 * Store analytics events
 *
 * Stores a bounded batch of pseudonymous extension analytics events for the signed-in user.
 */
export const postV1AnalyticsEvents = <ThrowOnError extends boolean = false>(
  options: Options<PostV1AnalyticsEventsData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PostV1AnalyticsEventsResponses,
    PostV1AnalyticsEventsErrors,
    ThrowOnError
  >({
    url: "/v1/analytics/events",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get analytics dashboard data
 *
 * Returns aggregate extension activity for the selected rolling time range.
 */
export const getV1AdminAnalytics = <ThrowOnError extends boolean = false>(
  options?: Options<GetV1AdminAnalyticsData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetV1AdminAnalyticsResponses,
    GetV1AdminAnalyticsErrors,
    ThrowOnError
  >({ url: "/v1/admin/analytics", ...options });

/**
 * Get analytics dashboard data
 *
 * Returns aggregate extension activity for the selected rolling time range.
 */
export const headV1AdminAnalytics = <ThrowOnError extends boolean = false>(
  options?: Options<HeadV1AdminAnalyticsData, ThrowOnError>,
) =>
  (options?.client ?? client).head<
    HeadV1AdminAnalyticsResponses,
    HeadV1AdminAnalyticsErrors,
    ThrowOnError
  >({ url: "/v1/admin/analytics", ...options });
