// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: "http://localhost:3000" | (string & {});
};

export type GetV1MeData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/v1/me";
};

export type GetV1MeErrors = {
  /**
   * GET /v1/me Negative response
   */
  400: {
    status: "error";
    error: {
      message: string;
    };
  };
};

export type GetV1MeError = GetV1MeErrors[keyof GetV1MeErrors];

export type GetV1MeResponses = {
  /**
   * GET /v1/me Positive response
   */
  200: {
    status: "success";
    data: {
      id: string;
      name: string;
      email: string;
      emailVerified: boolean;
      image?: string;
      role: "user" | "admin";
      /**
       * Account creation timestamp
       */
      createdAt: string;
    };
  };
};

export type GetV1MeResponse = GetV1MeResponses[keyof GetV1MeResponses];

export type HeadV1MeData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/v1/me";
};

export type HeadV1MeErrors = {
  /**
   * HEAD /v1/me Negative response
   */
  400: unknown;
};

export type HeadV1MeResponses = {
  /**
   * HEAD /v1/me Positive response
   */
  200: unknown;
};

export type PatchV1MeData = {
  /**
   * PATCH /v1/me Request body
   */
  body?: {
    /**
     * Display name
     */
    name?: string;
    image?: unknown;
  };
  path?: never;
  query?: never;
  url: "/v1/me";
};

export type PatchV1MeErrors = {
  /**
   * PATCH /v1/me Negative response
   */
  400: {
    status: "error";
    error: {
      message: string;
    };
  };
};

export type PatchV1MeError = PatchV1MeErrors[keyof PatchV1MeErrors];

export type PatchV1MeResponses = {
  /**
   * PATCH /v1/me Positive response
   */
  200: {
    status: "success";
    data: {
      /**
       * Whether the profile update succeeded
       */
      success: boolean;
      /**
       * Updated display name
       */
      name?: string;
      /**
       * Updated profile picture URL
       */
      image?: string;
    };
  };
};

export type PatchV1MeResponse = PatchV1MeResponses[keyof PatchV1MeResponses];

export type PostV1TtsSpeakData = {
  /**
   * POST /v1/tts/speak Request body
   */
  body: {
    text: string;
  };
  path?: never;
  query?: never;
  url: "/v1/tts/speak";
};

export type PostV1TtsSpeakErrors = {
  /**
   * POST /v1/tts/speak Negative response
   */
  400: {
    status: "error";
    error: {
      message: string;
    };
  };
};

export type PostV1TtsSpeakError =
  PostV1TtsSpeakErrors[keyof PostV1TtsSpeakErrors];

export type PostV1TtsSpeakResponses = {
  /**
   * POST /v1/tts/speak Positive response
   */
  200: {
    status: "success";
    data: {
      audio: string;
      codec: "wav";
      sampleRate: number;
      requestId?: string;
    };
  };
};

export type PostV1TtsSpeakResponse =
  PostV1TtsSpeakResponses[keyof PostV1TtsSpeakResponses];
