// This file is auto-generated by @hey-api/openapi-ts

import { queryOptions, type UseMutationOptions } from "@tanstack/react-query";

import { client } from "../client.gen";
import {
  getV1Me,
  getV1TtsVoices,
  type Options,
  patchV1Me,
  postV1TtsPlan,
  postV1TtsSpeak,
} from "../sdk.gen";
import type {
  GetV1MeData,
  GetV1MeError,
  GetV1MeResponse,
  GetV1TtsVoicesData,
  GetV1TtsVoicesError,
  GetV1TtsVoicesResponse,
  PatchV1MeData,
  PatchV1MeError,
  PatchV1MeResponse,
  PostV1TtsPlanData,
  PostV1TtsPlanError,
  PostV1TtsPlanResponse,
  PostV1TtsSpeakData,
  PostV1TtsSpeakError,
  PostV1TtsSpeakResponse,
} from "../types.gen";

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, "baseUrl" | "body" | "headers" | "path" | "query"> & {
    _id: string;
    _infinite?: boolean;
    tags?: ReadonlyArray<string>;
  },
];

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
  tags?: ReadonlyArray<string>,
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl:
      options?.baseUrl || (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (tags) {
    params.tags = tags;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return [params];
};

export const getV1MeQueryKey = (options?: Options<GetV1MeData>) =>
  createQueryKey("getV1Me", options);

/**
 * Get current user
 *
 * Returns the authenticated user's profile, including email verification status, role, and account creation date.
 */
export const getV1MeOptions = (options?: Options<GetV1MeData>) =>
  queryOptions<
    GetV1MeResponse,
    GetV1MeError,
    GetV1MeResponse,
    ReturnType<typeof getV1MeQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getV1Me({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getV1MeQueryKey(options),
  });

/**
 * Update profile
 *
 * Updates the authenticated user's profile fields (name and/or image).
 */
export const patchV1MeMutation = (
  options?: Partial<Options<PatchV1MeData>>,
): UseMutationOptions<
  PatchV1MeResponse,
  PatchV1MeError,
  Options<PatchV1MeData>
> => {
  const mutationOptions: UseMutationOptions<
    PatchV1MeResponse,
    PatchV1MeError,
    Options<PatchV1MeData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await patchV1Me({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getV1TtsVoicesQueryKey = (options?: Options<GetV1TtsVoicesData>) =>
  createQueryKey("getV1TtsVoices", options);

/**
 * List voices and narration options
 *
 * Returns the Bulbul models, their compatible voices, supported languages, narration tones, codecs and sample rates. Use this to populate voice pickers instead of hardcoding values.
 */
export const getV1TtsVoicesOptions = (options?: Options<GetV1TtsVoicesData>) =>
  queryOptions<
    GetV1TtsVoicesResponse,
    GetV1TtsVoicesError,
    GetV1TtsVoicesResponse,
    ReturnType<typeof getV1TtsVoicesQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getV1TtsVoices({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getV1TtsVoicesQueryKey(options),
  });

/**
 * Build a narration script
 *
 * Turns raw page text into an ordered list of narration-ready chunks: optional LLM clean-up, optional translation, then splitting at sentence boundaries within the TTS character limit. Returns no audio — call /v1/tts/speak per chunk and prefetch ahead of playback.
 */
export const postV1TtsPlanMutation = (
  options?: Partial<Options<PostV1TtsPlanData>>,
): UseMutationOptions<
  PostV1TtsPlanResponse,
  PostV1TtsPlanError,
  Options<PostV1TtsPlanData>
> => {
  const mutationOptions: UseMutationOptions<
    PostV1TtsPlanResponse,
    PostV1TtsPlanError,
    Options<PostV1TtsPlanData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postV1TtsPlan({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Synthesize one chunk
 *
 * Converts a single narration chunk into base64-encoded audio using Sarvam Bulbul. Text must be within the TTS character limit — use /v1/tts/plan to split longer content.
 */
export const postV1TtsSpeakMutation = (
  options?: Partial<Options<PostV1TtsSpeakData>>,
): UseMutationOptions<
  PostV1TtsSpeakResponse,
  PostV1TtsSpeakError,
  Options<PostV1TtsSpeakData>
> => {
  const mutationOptions: UseMutationOptions<
    PostV1TtsSpeakResponse,
    PostV1TtsSpeakError,
    Options<PostV1TtsSpeakData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postV1TtsSpeak({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};
