// This file is auto-generated by @hey-api/openapi-ts

import { queryOptions, type UseMutationOptions } from "@tanstack/react-query";

import { client } from "../client.gen";
import { getV1Me, type Options, patchV1Me } from "../sdk.gen";
import type {
  GetV1MeData,
  GetV1MeError,
  GetV1MeResponse,
  PatchV1MeData,
  PatchV1MeError,
  PatchV1MeResponse,
} from "../types.gen";

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, "baseUrl" | "body" | "headers" | "path" | "query"> & {
    _id: string;
    _infinite?: boolean;
    tags?: ReadonlyArray<string>;
  },
];

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
  tags?: ReadonlyArray<string>,
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl:
      options?.baseUrl || (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (tags) {
    params.tags = tags;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return [params];
};

export const getV1MeQueryKey = (options?: Options<GetV1MeData>) =>
  createQueryKey("getV1Me", options);

/**
 * Get current user
 *
 * Returns the authenticated user's profile, including email verification status, role, and account creation date.
 */
export const getV1MeOptions = (options?: Options<GetV1MeData>) =>
  queryOptions<
    GetV1MeResponse,
    GetV1MeError,
    GetV1MeResponse,
    ReturnType<typeof getV1MeQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getV1Me({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getV1MeQueryKey(options),
  });

/**
 * Update profile
 *
 * Updates the authenticated user's profile fields (name and/or image).
 */
export const patchV1MeMutation = (
  options?: Partial<Options<PatchV1MeData>>,
): UseMutationOptions<
  PatchV1MeResponse,
  PatchV1MeError,
  Options<PatchV1MeData>
> => {
  const mutationOptions: UseMutationOptions<
    PatchV1MeResponse,
    PatchV1MeError,
    Options<PatchV1MeData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await patchV1Me({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};
